language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

jdk:
  - oraclejdk13

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M test +assembly
  - docker build -t navicore/lots-of-names-api .

sudo: required

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push navicore/lots-of-names-api;
    docker tag "navicore/lots-of-names-api" "navicore/lots-of-names-api:0.1.$TRAVIS_BUILD_NUMBER";
    docker push "navicore/lots-of-names-api:0.1.$TRAVIS_BUILD_NUMBER";
    fi

