apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}
      labels:
        app: {{ .Values.affinity }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                    - {{ .Values.affinity }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
