name: Scala CI

on:
  push:
    branches: 
    - main
    tags:
    - v0.*
    - v1.*
    - v2.*
    - v3.*
    - v4.*
    - v5.*
  pull_request:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    - name: Run tests and Build superjar
      run: sbt assembly
    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: navicore/lots-of-names-api
        tag_with_ref: true
        tag_with_sha: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
